"""Persistent, deterministic, offline-only paper execution for Phase 12."""

from hyperlab.paper.carry_strategy import (
    PHASE05_CARRY_STRATEGY_ID,
    FrozenCashAndCarryPaperConfig,
    FrozenCashAndCarryPaperStrategy,
    make_phase05_paper_strategy_config,
)
from hyperlab.paper.engine import PaperCommandResult, PaperEngine
from hyperlab.paper.gate import (
    PaperGateEvidence,
    PaperGateResult,
    PaperGateStatus,
    evaluate_paper_gate,
)
from hyperlab.paper.models import (
    AlertSeverity,
    DecisionAction,
    DecisionIntent,
    LedgerEntry,
    MarketEvent,
    OrderIntent,
    OrderSide,
    OrderStatus,
    PaperEvent,
    PaperEventType,
    PaperExecutionConfig,
    PaperOrderType,
    PaperProjection,
    PaperRiskLimits,
    PaperRunConfig,
    PaperState,
    PaperStrategyConfig,
    PaperStrategyProjection,
    StoredPaperEvent,
    TimeInForce,
    deterministic_id,
    keyed_uniform,
)
from hyperlab.paper.phase05_portfolio import (
    Phase05Phase08PaperFoundation,
    Phase05Phase08RiskAllocation,
    build_phase05_phase08_paper_foundation,
    default_phase05_phase08_risk_allocation,
)
from hyperlab.paper.risk import RiskDecision, evaluate_order_risk, is_risk_reducing
from hyperlab.paper.runner import (
    FrozenPaperStrategy,
    PaperRunner,
    PaperRunnerResult,
    PaperStrategyView,
    PortfolioRunner,
)
from hyperlab.paper.store import (
    AppendResult,
    ConcurrentWriteError,
    IdempotencyConflictError,
    InputRecord,
    IntegrityError,
    LedgerImbalanceError,
    PaperStore,
    RunConflictError,
    RunNotFoundError,
    SchemaVersionError,
)

__all__ = [
    "PHASE05_CARRY_STRATEGY_ID",
    "AlertSeverity",
    "AppendResult",
    "ConcurrentWriteError",
    "DecisionAction",
    "DecisionIntent",
    "FrozenCashAndCarryPaperConfig",
    "FrozenCashAndCarryPaperStrategy",
    "FrozenPaperStrategy",
    "IdempotencyConflictError",
    "InputRecord",
    "IntegrityError",
    "LedgerEntry",
    "LedgerImbalanceError",
    "MarketEvent",
    "OrderIntent",
    "OrderSide",
    "OrderStatus",
    "PaperCommandResult",
    "PaperEngine",
    "PaperEvent",
    "PaperEventType",
    "PaperExecutionConfig",
    "PaperGateEvidence",
    "PaperGateResult",
    "PaperGateStatus",
    "PaperOrderType",
    "PaperProjection",
    "PaperRiskLimits",
    "PaperRunConfig",
    "PaperRunner",
    "PaperRunnerResult",
    "PaperState",
    "PaperStore",
    "PaperStrategyConfig",
    "PaperStrategyProjection",
    "PaperStrategyView",
    "Phase05Phase08PaperFoundation",
    "Phase05Phase08RiskAllocation",
    "PortfolioRunner",
    "RiskDecision",
    "RunConflictError",
    "RunNotFoundError",
    "SchemaVersionError",
    "StoredPaperEvent",
    "TimeInForce",
    "build_phase05_phase08_paper_foundation",
    "default_phase05_phase08_risk_allocation",
    "deterministic_id",
    "evaluate_order_risk",
    "evaluate_paper_gate",
    "is_risk_reducing",
    "keyed_uniform",
    "make_phase05_paper_strategy_config",
]
